name: gsec
description: A comprehensive Flutter application for device security, ownership verification, and peer-to-peer trading.

# Application version and build number
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Core dependencies
  crypto: ^3.0.3
  
  # UI and Layout
  flutter_staggered_grid_view: ^0.6.2
  hidden_drawer_menu: ^3.0.1
  liquid_progress_indicator: ^0.4.0
  awesome_dialog: ^3.0.2
  bouncing_widget: ^2.0.0
  cached_network_image: ^3.2.3
  
  # Payment and Commerce
  square_in_app_payments: ^3.0.0
  
  # Utilities
  fluttertoast: ^8.2.2
  url_launcher: ^6.1.12
  qr_flutter: ^4.1.0
  font_awesome_flutter: ^10.5.0
  country_code_picker: ^3.0.0
  
  # File and Media Handling
  file_picker: ^5.3.4
  image_cropper: ^4.0.1
  image_picker: ^1.0.4
  
  # Communication
  flutter_sms: ^2.3.3
  
  # State Management
  provider: ^6.0.5
  
  # Device and Platform
  device_info_plus: ^9.1.0
  shared_preferences: ^2.2.0
  
  # Firebase Services
  cloud_firestore: ^4.9.1
  firebase_core: ^2.15.1
  firebase_storage: ^11.2.6
  firebase_auth: ^4.9.0
  
  # Authentication
  flutter_signin_button: ^2.0.0
  google_sign_in: ^6.1.4
  
  # Icons and Fonts
  cupertino_icons: ^1.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.3

# Flutter configuration
flutter:
  uses-material-design: true
  
  assets:
    - assets/
    - icons/

  fonts:
    - family: pacifico
      fonts:
        - asset: fonts/pacifico/Pacifico.ttf
